level_0 = {
    'terrain': 'src/code/levels/0/level_0_terrain.csv',
    'player': 'src/code/levels/0/level_0_player.csv',
    'fg palms': 'src/code/levels/0/level_0_fg_palms.csv',
    'enemies': 'src/code/levels/0/level_0_enemies.csv',
    'crates': 'src/code/levels/0/level_0_crates.csv',
    'constraints': 'src/code/levels/0/level_0_constraints.csv',
    'coins': 'src/code/levels/0/level_0_coins.csv',
    'bg palms': 'src/code/levels/0/level_0_bg_palms.csv',
    'node_pos': (110,400),
    'unlock': 1,
    'node_graphics': 'src/code/levels/graphics/overworld/0'}
level_1 = {
    'terrain': 'src/code/levels/0/level_0_terrain.csv',
    'player': 'src/code/levels/0/level_0_player.csv',
    'fg palms': 'src/code/levels/0/level_0_fg_palms.csv',
    'enemies': 'src/code/levels/0/level_0_enemies.csv',
    'crates': 'src/code/levels/0/level_0_crates.csv',
    'constraints': 'src/code/levels/0/level_0_constraints.csv',
    'coins': 'src/code/levels/0/level_0_coins.csv',
    'bg palms': 'src/code/levels/0/level_0_bg_palms.csv',
    'node_pos': (300,220),
    'unlock': 2,
    'node_graphics': 'src/code/levels/graphics/overworld/1'}
level_2 = {
    'terrain': 'src/code/levels/0/level_0_terrain.csv',
    'player': 'src/code/levels/0/level_0_player.csv',
    'fg palms': 'src/code/levels/0/level_0_fg_palms.csv',
    'enemies': 'src/code/levels/0/level_0_enemies.csv',
    'crates': 'src/code/levels/0/level_0_crates.csv',
    'constraints': 'src/code/levels/0/level_0_constraints.csv',
    'coins': 'src/code/levels/0/level_0_coins.csv',
    'bg palms': 'src/code/levels/0/level_0_bg_palms.csv',
    'node_pos': (480,610),
    'unlock': 3,
    'node_graphics': 'src/code/levels/graphics/overworld/2'}
level_3 = {
    'terrain': 'src/code/levels/0/level_0_terrain.csv',
    'player': 'src/code/levels/0/level_0_player.csv',
    'fg palms': 'src/code/levels/0/level_0_fg_palms.csv',
    'enemies': 'src/code/levels/0/level_0_enemies.csv',
    'crates': 'src/code/levels/0/level_0_crates.csv',
    'constraints': 'src/code/levels/0/level_0_constraints.csv',
    'coins': 'src/code/levels/0/level_0_coins.csv',
    'bg palms': 'src/code/levels/0/level_0_bg_palms.csv',
    'node_pos': (610,350),
    'unlock': 4,
    'node_graphics': 'src/code/levels/graphics/overworld/3'}
level_4 = {
    'terrain': 'src/code/levels/0/level_0_terrain.csv',
    'player': 'src/code/levels/0/level_0_player.csv',
    'fg palms': 'src/code/levels/0/level_0_fg_palms.csv',
    'enemies': 'src/code/levels/0/level_0_enemies.csv',
    'crates': 'src/code/levels/0/level_0_crates.csv',
    'constraints': 'src/code/levels/0/level_0_constraints.csv',
    'coins': 'src/code/levels/0/level_0_coins.csv',
    'bg palms': 'src/code/levels/0/level_0_bg_palms.csv',
    'node_pos': (880,210),
    'unlock': 5,
    'node_graphics': 'src/code/levels/graphics/overworld/4'}
level_5 = {
    'terrain': 'src/code/levels/0/level_0_terrain.csv',
    'player': 'src/code/levels/0/level_0_player.csv',
    'fg palms': 'src/code/levels/0/level_0_fg_palms.csv',
    'enemies': 'src/code/levels/0/level_0_enemies.csv',
    'crates': 'src/code/levels/0/level_0_crates.csv',
    'constraints': 'src/code/levels/0/level_0_constraints.csv',
    'coins': 'src/code/levels/0/level_0_coins.csv',
    'bg palms': 'src/code/levels/0/level_0_bg_palms.csv',
    'node_pos': (1050,400),
    'unlock': 5,
    'node_graphics': 'src/code/levels/graphics/overworld/5'}

levels = {
    0: level_0,
    1: level_1,
    2: level_2,
    3: level_3,
    4: level_4,
    5: level_5}