level_0 = {
    'terrain': 'src/code/levels/0/0_terrain.csv',
    'player': 'src/code/levels/0/0_player.csv',
    'fg palms': 'src/code/levels/0/0_fg palms.csv',
    'enemies': 'src/code/levels/0/0_enemies.csv',
    'crates': 'src/code/levels/0/0_crates.csv',
    'constraints': 'src/code/levels/0/0_constraints.csv',
    'coins': 'src/code/levels/0/0_coins.csv',
    'bg palms': 'src/code/levels/0/0_bg palms.csv',
    'node_pos': (110,400),
    'unlock': 1,
    'node_graphics': 'src/code/levels/graphics/overworld/0'}
level_1 = {
    'terrain': 'src/code/levels/1/1_terrain.csv',
    'player': 'src/code/levels/1/1_player.csv',
    'fg palms': 'src/code/levels/1/1_fg palms.csv',
    'enemies': 'src/code/levels/1/1_enemies.csv',
    'crates': 'src/code/levels/1/1_crates.csv',
    'constraints': 'src/code/levels/1/1_constraints.csv',
    'coins': 'src/code/levels/1/1_coins.csv',
    'bg palms': 'src/code/levels/1/1_bg palms.csv',
    'node_pos': (300,220),
    'unlock': 2,
    'node_graphics': 'src/code/levels/graphics/overworld/1'}
level_2 = {
    'terrain': 'src/code/levels/2/2_terrain.csv',
    'player': 'src/code/levels/2/2_player.csv',
    'fg palms': 'src/code/levels/2/2_fg palms.csv',
    'enemies': 'src/code/levels/2/2_enemies.csv',
    'crates': 'src/code/levels/2/2_crates.csv',
    'constraints': 'src/code/levels/2/2_constraints.csv',
    'coins': 'src/code/levels/2/2_coins.csv',
    'bg palms': 'src/code/levels/2/2_bg palms.csv',
    'node_pos': (480,610),
    'unlock': 3,
    'node_graphics': 'src/code/levels/graphics/overworld/2'}
level_3 = {
    'terrain': 'src/code/levels/3/3_terrain.csv',
    'player': 'src/code/levels/3/3_player.csv',
    'fg palms': 'src/code/levels/3/3_fg palms.csv',
    'enemies': 'src/code/levels/3/3_enemies.csv',
    'crates': 'src/code/levels/3/3_crates.csv',
    'constraints': 'src/code/levels/3/3_constraints.csv',
    'coins': 'src/code/levels/3/3_coins.csv',
    'bg palms': 'src/code/levels/3/3_bg palms.csv',
    'node_pos': (610,350),
    'unlock': 4,
    'node_graphics': 'src/code/levels/graphics/overworld/3'}
level_4 = {
    'terrain': 'src/code/levels/0/0_terrain.csv',
    'player': 'src/code/levels/0/0_player.csv',
    'fg palms': 'src/code/levels/0/0_fg palms.csv',
    'enemies': 'src/code/levels/0/0_enemies.csv',
    'crates': 'src/code/levels/0/0_crates.csv',
    'constraints': 'src/code/levels/0/0_constraints.csv',
    'coins': 'src/code/levels/0/0_coins.csv',
    'bg palms': 'src/code/levels/0/0_bg palms.csv',
    'node_pos': (880,210),
    'unlock': 5,
    'node_graphics': 'src/code/levels/graphics/overworld/4'}
level_5 = {
    'terrain': 'src/code/levels/0/0_terrain.csv',
    'player': 'src/code/levels/0/0_player.csv',
    'fg palms': 'src/code/levels/0/0_fg palms.csv',
    'enemies': 'src/code/levels/0/0_enemies.csv',
    'crates': 'src/code/levels/0/0_crates.csv',
    'constraints': 'src/code/levels/0/0_constraints.csv',
    'coins': 'src/code/levels/0/0_coins.csv',
    'bg palms': 'src/code/levels/0/0_bg palms.csv',
    'node_pos': (1050,400),
    'unlock': 5,
    'node_graphics': 'src/code/levels/graphics/overworld/5'}

levels = {
    0: level_0,
    1: level_1,
    2: level_2,
    3: level_3,
    4: level_4,
    5: level_5}